from pathlib import Path
import json

MODULES = {
"01_chemistry_foundations": [
"What chemistry studies", "Macroscopic, microscopic, and symbolic views", "Matter as particles in motion", "Physical versus chemical properties", "Physical versus chemical changes", "Elements, compounds, and mixtures", "Homogeneous and heterogeneous mixtures", "Separating mixtures by physical properties", "Filtration and particle size", "Distillation and boiling point", "Chromatography and molecular attraction", "Crystallization and solubility", "Sublimation as a separation method", "Centrifugation and density", "Decanting and sedimentation", "Why models help chemists", "Evidence and explanation in chemistry", "Conservation of mass", "Conservation of energy", "Scale in chemistry", "Chemical symbols as shorthand", "Reading a chemical formula", "Reading a chemical equation", "The meaning of a coefficient", "The meaning of a subscript", "States of matter in equations", "Energy diagrams as chemical stories", "Chemical systems and surroundings", "Open, closed, and isolated systems", "The role of measurement", "Units as a language", "Significant figures as information", "Dimensional analysis", "Estimating before calculating", "Orders of magnitude in chemistry", "Chemistry in cooking", "Chemistry in medicine", "Chemistry in materials", "Chemistry and sustainability", "How to think like a chemist"],
"02_measurement_and_math": [
"SI base units in chemistry", "Derived units and density", "Reading a graduated cylinder", "Meniscus and parallax", "Mass versus weight", "Temperature scales", "Kelvin and absolute temperature", "Converting temperature units", "Precision versus accuracy", "Random versus systematic error", "Percent error", "Percent difference", "Significant figures in multiplication", "Significant figures in addition", "Exact versus measured numbers", "Scientific notation", "Logarithms in chemistry", "Antilogarithms and powers of ten", "Ratios and proportions", "Solving one-step chemical equations", "Rearranging formulas", "Graphing experimental data", "Slope as a rate", "Intercept and meaning", "Linearization of data", "Reading a calibration curve", "Uncertainty propagation basics", "Mean and median", "Standard deviation concept", "Outliers and data quality", "Dimensional analysis for recipes", "Density problem strategy", "Molarity calculation strategy", "Dilution calculation strategy", "Temperature conversion practice", "Pressure unit conversions", "Energy unit conversions", "Chemistry with percentages", "Checking units in an answer", "Checking whether an answer is reasonable"],
"03_atomic_theory": [
"Democritus and the atom idea", "Dalton's atomic theory", "Cathode rays and electrons", "Millikan's oil-drop experiment", "Rutherford's gold foil experiment", "The nuclear atom", "Protons, neutrons, and electrons", "Atomic number", "Mass number", "Isotopes", "Writing isotope symbols", "Average atomic mass", "Calculating weighted averages", "Cations and anions", "Ions and electron count", "Monatomic ions", "Polyatomic ions", "Atomic mass units", "The mole as a counting unit", "Avogadro's number", "Molar mass from the periodic table", "Atoms to moles", "Moles to particles", "Mass to moles", "Moles to mass", "Isotope abundance spectra", "Why isotopes have the same chemistry", "Radioisotopes in tracing", "Nuclear versus chemical change", "Atomic notation practice", "Counting subatomic particles", "Neutral atoms and charge balance", "Ion formation patterns", "Why nuclei are small", "Nuclear force overview", "Mass defect concept", "Binding energy concept", "Atomic theory as a changing model", "What an atomic number tells you", "What a mass number tells you"],
"04_quantum_and_electronic_structure": [
"Light as electromagnetic radiation", "Wavelength and frequency", "The speed of light relationship", "Photon energy", "The electromagnetic spectrum", "Blackbody radiation", "The photoelectric effect", "Bohr's model", "Hydrogen emission lines", "Energy levels and transitions", "Why Bohr's model is limited", "Matter waves", "The uncertainty principle", "Quantum numbers", "Principal quantum number", "Angular momentum quantum number", "Magnetic quantum number", "Spin quantum number", "Atomic orbitals", "s orbitals", "p orbitals", "d orbitals", "f orbitals", "Orbital shapes", "Nodes in orbitals", "Electron spin", "Pauli exclusion principle", "Aufbau principle", "Hund's rule", "Writing electron configurations", "Noble-gas shorthand", "Exceptions in transition metals", "Valence electrons", "Core electrons", "Paramagnetism", "Diamagnetism", "Electron configurations of ions", "Ground state versus excited state", "Spectra as fingerprints", "Quantum ideas in modern chemistry"],
"05_periodicity": [
"Reading the periodic table", "Periods and groups", "Metals, nonmetals, and metalloids", "Main-group families", "Alkali metals", "Alkaline earth metals", "Chalcogens", "Halogens", "Noble gases", "Transition metals", "Lanthanides", "Actinides", "Atomic radius", "Why atomic radius changes across a period", "Why atomic radius changes down a group", "Ionic radius", "Cation size versus atom size", "Anion size versus atom size", "Ionization energy", "Successive ionization energies", "Electron affinity", "Electronegativity", "Metallic character", "Shielding effect", "Effective nuclear charge", "Periodic trends as competing effects", "Predicting common ion charges", "Isoelectronic series", "Reactivity of alkali metals", "Reactivity of halogens", "Why noble gases are unreactive", "Oxidation states and periodicity", "Diagonal relationships", "Periodic trends in oxides", "Acidic and basic oxides", "Hydrogen's unusual position", "Metals as electron donors", "Nonmetals as electron acceptors", "Limits of simple periodic trends", "The periodic table as a map"],
"06_chemical_bonding": [
"Why atoms form bonds", "Ionic bonding", "Covalent bonding", "Metallic bonding", "Lattice energy", "Born-Haber cycle idea", "Bond energy", "Bond length", "Bond order", "Polar covalent bonds", "Electronegativity difference", "Dipole moments", "Drawing Lewis symbols", "Lewis structures for ions", "Octet rule", "Incomplete octets", "Expanded valence shells", "Odd-electron species", "Formal charge", "Choosing the best Lewis structure", "Resonance structures", "Resonance hybrid", "Coordinate covalent bonds", "Electron-deficient molecules", "Bond polarity arrows", "Ionic compounds and formulas", "Properties of ionic solids", "Properties of molecular substances", "Properties of metals", "Network covalent solids", "Bonding and conductivity", "Bonding and melting point", "Bonding models compared", "Limitations of the octet rule", "Chemical bonds as energy changes", "Breaking and forming bonds", "Bonding in hydrogen", "Bonding in oxygen", "Bonding in nitrogen", "Bonding as electron redistribution"],
"07_shape_polarity_and_forces": [
"VSEPR theory", "Electron domains", "Linear molecular geometry", "Trigonal planar geometry", "Tetrahedral geometry", "Trigonal pyramidal geometry", "Bent molecular geometry", "Trigonal bipyramidal geometry", "Seesaw geometry", "T-shaped geometry", "Linear from five domains", "Octahedral geometry", "Square pyramidal geometry", "Square planar geometry", "Lone pairs and bond angles", "Molecular shape versus electron geometry", "Molecular polarity", "Symmetry and dipole cancellation", "Intermolecular forces", "London dispersion forces", "Dipole-dipole forces", "Hydrogen bonding", "Ion-dipole forces", "Comparing intermolecular forces", "Boiling point and attraction", "Surface tension", "Viscosity", "Capillary action", "Vapor pressure", "Volatility", "Solubility and polarity", "Like dissolves like", "Hydrophobic and hydrophilic groups", "Molecular shape and smell", "Forces between biomolecules", "Why water is unusual", "Ice and liquid water", "Intermolecular forces in proteins", "Predicting physical properties", "A force-based view of matter"],
"08_formulas_and_nomenclature": [
"Naming ionic compounds", "Naming cations with fixed charge", "Naming variable-charge metals", "Naming ionic compounds with polyatomic ions", "Naming binary molecular compounds", "Prefixes for molecular compounds", "Naming acids", "Naming binary acids", "Naming oxyacids", "Naming bases", "Naming hydrates", "Naming simple hydrocarbons", "Naming alkanes", "Naming alkenes", "Naming alkynes", "Naming alcohols", "Naming ethers", "Naming aldehydes", "Naming ketones", "Naming carboxylic acids", "Naming esters", "Naming amines", "Naming amides", "Naming aromatic compounds", "Writing formulas from names", "Formula mass", "Empirical formulas", "Molecular formulas", "Combustion analysis", "Percent composition", "Oxidation-state naming", "Common ions reference strategy", "Charge balance in formulas", "Structural versus molecular formulas", "Condensed structural formulas", "Line-angle notation", "Stereochemical descriptors overview", "IUPAC names versus common names", "Avoiding nomenclature traps", "Chemical language as a decoding skill"],
"09_stoichiometry_and_reactions": [
"Balancing chemical equations", "Why atoms must balance", "Coefficients versus subscripts", "Classifying reaction patterns", "Synthesis reactions", "Decomposition reactions", "Single replacement", "Double replacement", "Combustion reactions", "Acid-base neutralization", "Precipitation reactions", "Gas-forming reactions", "Net ionic equations", "Spectator ions", "Mole ratios", "Stoichiometry roadmap", "Mass-to-mass calculations", "Mole-to-mole calculations", "Limiting reactant", "Excess reactant", "Theoretical yield", "Actual yield", "Percent yield", "Reaction stoichiometry with solutions", "Reaction stoichiometry with gases", "Stoichiometry with purity", "Sequential reactions", "Overall reaction from steps", "Redox reaction recognition", "Oxidation numbers", "Oxidation versus reduction", "Disproportionation", "Stoichiometric coefficients and scale", "Chemical equation interpretation", "Combustion analysis workflow", "Precipitation stoichiometry", "Neutralization stoichiometry", "Error sources in yield", "Checking a balanced equation", "Stoichiometry problem strategy"],
"10_solutions": [
"What a solution is", "Solute and solvent", "Aqueous solutions", "Electrolytes", "Strong versus weak electrolytes", "Nonelectrolytes", "Dissolution at the particle level", "Hydration shells", "Solubility", "Solubility rules", "Molarity", "Molality", "Mole fraction", "Mass percent", "Parts per million", "Parts per billion", "Preparing a solution", "Dilution", "Serial dilution", "Mixing solutions", "Solution stoichiometry", "Precipitation from mixed solutions", "Solubility and temperature", "Gas solubility", "Henry's law", "Saturated solutions", "Unsaturated solutions", "Supersaturated solutions", "Dynamic dissolution equilibrium", "Colligative properties", "Boiling point elevation", "Freezing point depression", "Osmotic pressure", "Van't Hoff factor", "Electrolyte particle counting", "Describing concentration correctly", "Why salt dissolves in water", "Why oil and water separate", "Solutions in cells", "Solutions in everyday products"],
"11_gases": [
"Gas pressure", "Atmospheric pressure", "Manometers", "Barometers", "Boyle's law", "Charles's law", "Avogadro's law", "Combined gas law", "Ideal gas law", "Gas density", "Molar mass of a gas", "Gas stoichiometry", "Gas volume at STP", "Partial pressure", "Dalton's law", "Mole fraction in gas mixtures", "Gas collection over water", "Water vapor correction", "Kinetic molecular theory", "Temperature and molecular speed", "Pressure at the particle level", "Volume at the particle level", "Gas diffusion", "Gas effusion", "Graham's law", "Real gases", "Why gases deviate", "Intermolecular attractions in gases", "Van der Waals equation", "Critical temperature", "Critical pressure", "Liquefaction of gases", "Gas laws in breathing", "Gas laws in weather", "Gas laws in engines", "Greenhouse gases", "Atmospheric composition", "Gas solubility and diving", "Partial pressure in blood", "Solving multistep gas problems"],
"12_liquids_and_solids": [
"Properties of liquids", "Cohesion and adhesion", "Surface tension", "Viscosity and temperature", "Vapor pressure", "Boiling and external pressure", "Heating curves", "Cooling curves", "Phase diagrams", "Triple point", "Critical point", "Fusion curves", "Sublimation curves", "Dynamic phase equilibrium", "Enthalpy of fusion", "Enthalpy of vaporization", "Heating a substance calculation", "Crystalline solids", "Amorphous solids", "Unit cells", "Simple cubic packing", "Body-centered cubic packing", "Face-centered cubic packing", "Close packing", "Coordination number", "Packing efficiency", "Density of a unit cell", "Ionic crystal structures", "Covalent network solids", "Molecular solids", "Metallic solids", "Semiconductors", "Band theory overview", "Defects in crystals", "Doping a semiconductor", "Polymorphism", "Solids and material properties", "Phase changes in climate", "Why ice floats", "Matter as a changing lattice"],
"13_thermochemistry": [
"Energy in chemical systems", "Kinetic and potential energy", "Internal energy", "System and surroundings", "Heat versus temperature", "Exothermic processes", "Endothermic processes", "The first law", "Work and heat", "Pressure-volume work", "Enthalpy", "Enthalpy change", "Calorimetry", "Specific heat capacity", "Heat capacity", "Coffee-cup calorimetry", "Bomb calorimetry", "Calorimetry calculations", "Heating curves and energy", "Phase-change energy", "Hess's law", "Enthalpy from formation data", "Standard enthalpy of formation", "Bond enthalpy estimates", "Combustion enthalpy", "Food energy", "Fuel energy", "Energy efficiency", "Thermochemical equations", "State functions", "Path independence", "Energy diagrams", "Reaction coordinate and heat", "Thermal pollution", "Energy in metabolism", "Energy in batteries", "Energy and climate", "Calorimeter error sources", "Reasoning about energy signs", "Thermochemistry problem strategy"],
"14_thermodynamics": [
"The second law", "Entropy as dispersal", "Microstates", "Boltzmann's idea", "Entropy changes in phase changes", "Entropy and mixing", "Entropy of reactions", "Standard molar entropy", "The third law", "Spontaneous processes", "Spontaneous does not mean fast", "Free energy", "Gibbs free energy", "Free-energy sign conventions", "Free energy from enthalpy and entropy", "Free energy and temperature", "Free energy and equilibrium", "Chemical potential", "Standard free-energy change", "Free energy of formation", "Reaction direction", "Coupled reactions", "Energy coupling in cells", "Equilibrium as minimum free energy", "Reversible and irreversible processes", "Heat engines", "Efficiency limits", "Carnot cycle concept", "Refrigerators and heat pumps", "Thermodynamics of dissolving", "Thermodynamics of folding", "Thermodynamics of membranes", "Thermodynamics of phase separation", "Thermodynamics and solubility", "Thermodynamics of batteries", "Thermodynamics of life", "Entropy and information", "Why order can emerge locally", "Free energy as a driving force", "Thermodynamics synthesis"],
"15_kinetics": [
"Reaction rate", "Average rate", "Instantaneous rate", "Rate from concentration data", "Rate laws", "Reaction order", "Zero-order reactions", "First-order reactions", "Second-order reactions", "Integrated rate laws", "Half-life", "Half-life and order", "Method of initial rates", "Graphical order tests", "Rate constants", "Temperature and rate", "Collision theory", "Activation energy", "Arrhenius equation", "Arrhenius plots", "Transition states", "Activated complexes", "Catalysts", "Homogeneous catalysis", "Heterogeneous catalysis", "Enzymes as catalysts", "Reaction mechanisms", "Elementary steps", "Molecularity", "Rate-determining step", "Intermediates", "Steady-state approximation", "Pre-equilibrium approximation", "Mechanism from a rate law", "Rate law from a mechanism", "Photochemical reactions", "Diffusion-controlled reactions", "Surface area and rate", "Kinetics in everyday life", "Kinetics problem strategy"],
"16_equilibrium": [
"Dynamic equilibrium", "Equilibrium at the particle level", "Equilibrium constants", "Writing K expressions", "Kc versus Kp", "Homogeneous equilibrium", "Heterogeneous equilibrium", "Reaction quotient", "Predicting reaction direction", "ICE tables", "Solving equilibrium with change", "Small-x approximation", "Quadratic equilibrium problems", "Le Châtelier's principle", "Concentration stress", "Pressure stress", "Volume stress", "Temperature stress", "Catalysts and equilibrium", "Inert gases and equilibrium", "Adding solids and liquids", "Equilibrium and free energy", "Equilibrium and rate", "Multiple equilibria", "Coupled equilibria", "Equilibrium in solution", "Complex-ion equilibria", "Gas-phase equilibrium", "Industrial equilibrium", "Haber process equilibrium", "Contact process equilibrium", "Equilibrium and color", "Equilibrium and solubility", "Equilibrium and acid-base chemistry", "Equilibrium approximations", "Common equilibrium mistakes", "Equilibrium graph reading", "Disturbance and response", "Equilibrium problem strategy", "Equilibrium as balance"],
"17_acids_and_bases": [
"Arrhenius acids and bases", "Brønsted-Lowry acids and bases", "Lewis acids and bases", "Conjugate acid-base pairs", "Amphiprotic species", "Water autoionization", "Kw", "pH", "pOH", "Converting pH and concentration", "Strong acids", "Strong bases", "Weak acids", "Weak bases", "Ka", "Kb", "pKa", "pKb", "Percent ionization", "Acid strength and structure", "Base strength and structure", "Polyprotic acids", "Amphiprotic pH", "Common-ion effect", "Buffers", "Henderson-Hasselbalch equation", "Buffer capacity", "Buffer design", "Buffer failure", "Acid-base titrations", "Titration curves", "Equivalence point", "Half-equivalence point", "Indicators", "Strong acid-strong base titration", "Weak acid-strong base titration", "Strong acid-weak base titration", "Polyprotic titration", "Acid-base problem strategy", "Acid-base chemistry in life"],
"18_solubility_and_complexation": [
"Solubility equilibria", "Ksp", "Writing Ksp expressions", "Molar solubility", "Ksp and precipitation", "Ion product Qsp", "Selective precipitation", "Common-ion effect on solubility", "pH and solubility", "Solubility of hydroxides", "Solubility of carbonates", "Solubility of sulfides", "Complex-ion formation", "Formation constants", "Overall equilibrium constants", "Amphoterism and solubility", "Chelation", "EDTA complexes", "Hard and soft metal ions", "Coordination number", "Ligands", "Monodentate ligands", "Bidentate ligands", "Polydentate ligands", "Geometric isomers in complexes", "Color in coordination compounds", "Magnetism in complexes", "Crystal-field splitting", "Tetrahedral versus octahedral fields", "High-spin and low-spin", "Complexometric titration", "Metal ion buffering", "Water hardness", "Scale and precipitation", "Mineral weathering", "Biomineralization", "Metal transport in biology", "Solubility problem strategy", "Equilibrium networks", "From ions to minerals"],
"19_redox_and_electrochemistry": [
"Oxidation and reduction", "Oxidation numbers", "Assigning oxidation states", "Redox agents", "Oxidizing agents", "Reducing agents", "Balancing redox in acid", "Balancing redox in base", "Half-reaction method", "Galvanic cells", "Voltaic cells", "Anode and cathode", "Electron flow in a wire", "Ion flow through a salt bridge", "Cell notation", "Standard reduction potentials", "Predicting spontaneity", "Standard cell potential", "Free energy and cell potential", "Nernst equation", "Concentration cells", "Electrolytic cells", "Electrolysis", "Faraday's law", "Electroplating", "Molten-salt electrolysis", "Aqueous electrolysis", "Overpotential", "Batteries", "Alkaline batteries", "Lead-acid batteries", "Lithium-ion batteries", "Fuel cells", "Hydrogen fuel cells", "Corrosion", "Galvanic corrosion", "Cathodic protection", "Redox titrations", "Electrochemical sensors", "Electrochemistry problem strategy"],
"20_inorganic_chemistry": [
"Inorganic chemistry scope", "Hydrogen chemistry", "Hydrides", "Alkali-metal compounds", "Alkaline-earth compounds", "Group 13 chemistry", "Boranes", "Aluminum chemistry", "Carbon allotropes", "Silicon and silicates", "Group 15 trends", "Ammonia chemistry", "Nitrogen oxides", "Phosphorus chemistry", "Group 16 trends", "Sulfur oxides", "Sulfuric acid", "Oxygen allotropes", "Group 17 trends", "Interhalogen compounds", "Noble-gas compounds", "Transition-metal chemistry", "Transition-metal oxidation states", "Coordination compounds", "Ligand substitution", "Trans effect overview", "Organometallic compounds", "Metal carbonyls", "Metals in catalysis", "Lanthanide contraction", "Lanthanide chemistry", "Actinide chemistry", "f-block magnetism", "Bioinorganic metal centers", "Iron in hemoglobin", "Copper proteins", "Zinc enzymes", "Inorganic pigments", "Inorganic acids and bases", "Periodic trends in inorganic reactions"],
"21_organic_foundations": [
"Why carbon forms so many compounds", "Carbon hybridization", "sp3 carbon", "sp2 carbon", "sp carbon", "Sigma bonds", "Pi bonds", "Constitutional isomers", "Stereoisomers", "Conformations", "Newman projections", "Cyclohexane chairs", "Axial and equatorial positions", "Cis-trans isomerism", "E-Z notation", "R-S configuration", "Chirality", "Enantiomers", "Diastereomers", "Meso compounds", "Racemates", "Optical activity", "Acid-base ideas in organic chemistry", "Resonance in organic molecules", "Inductive effects", "Hyperconjugation", "Aromaticity", "Hückel's rule", "Benzene structure", "Electrophiles", "Nucleophiles", "Leaving groups", "Curved-arrow notation", "Organic reaction families", "Functional groups as reactivity hubs", "Organic oxidation states", "Spectroscopy as structure evidence", "Organic solubility", "Organic boiling points", "Organic chemistry problem strategy"],
"22_organic_reactions_and_mechanisms": [
"Alkane radical halogenation", "Alkene electrophilic addition", "Hydrogenation of alkenes", "Hydration of alkenes", "Hydrohalogenation", "Markovnikov's rule", "Anti-Markovnikov addition", "Halohydrin formation", "Epoxide formation", "Alkyne additions", "Aromatic electrophilic substitution", "Nitration of benzene", "Halogenation of benzene", "Friedel-Crafts alkylation", "Friedel-Crafts acylation", "Nucleophilic substitution", "SN2 mechanism", "SN1 mechanism", "E2 elimination", "E1 elimination", "Substitution versus elimination", "Alcohol oxidation", "Alcohol substitution", "Alcohol dehydration", "Ether synthesis", "Carbonyl nucleophilic addition", "Aldehyde oxidation", "Ketone reduction", "Acetal formation", "Grignard reactions", "Carboxylic acid derivatives", "Nucleophilic acyl substitution", "Esterification", "Ester hydrolysis", "Amide formation", "Amines and basicity", "Diazonium chemistry", "Aldol reactions", "Diels-Alder reaction", "Organic synthesis planning"],
"23_analytical_and_instrumental": [
"Analytical chemistry scope", "Qualitative versus quantitative analysis", "Sampling and representativeness", "Calibration and standards", "External calibration", "Internal standards", "Standard addition", "Limit of detection", "Limit of quantitation", "Selectivity and sensitivity", "Gravimetric analysis", "Precipitation gravimetry", "Volumetric analysis", "Primary standards", "Titrant standardization", "Endpoint versus equivalence", "UV-visible spectroscopy", "Beer-Lambert law", "Absorbance and transmittance", "UV-visible calibration curve", "Fluorescence spectroscopy", "Infrared spectroscopy", "IR functional-group regions", "NMR spectroscopy", "Chemical shift", "Spin-spin splitting", "Mass spectrometry", "Mass-to-charge ratio", "Isotope patterns in mass spectra", "Chromatography", "Thin-layer chromatography", "Gas chromatography", "High-performance liquid chromatography", "Retention time", "Chromatographic resolution", "Electroanalytical chemistry", "Potentiometry", "Ion-selective electrodes", "Error analysis in measurements", "Analytical workflow problem strategy"],
"24_biochemistry": [
"Biochemistry as molecular chemistry", "Water in biological systems", "Amino acids", "Zwitterions", "Peptide bonds", "Protein primary structure", "Protein secondary structure", "Protein tertiary structure", "Protein quaternary structure", "Protein folding", "Denaturation", "Enzyme active sites", "Enzyme catalysis", "Michaelis-Menten model", "Competitive inhibition", "Noncompetitive inhibition", "Allosteric regulation", "Carbohydrates", "Monosaccharides", "Disaccharides", "Polysaccharides", "Glycosidic bonds", "Lipids", "Fatty acids", "Phospholipids", "Micelles and bilayers", "Membrane fluidity", "Nucleotides", "DNA base pairing", "RNA structure", "ATP energy coupling", "NADH and electron transfer", "Glycolysis chemistry", "Citric acid cycle chemistry", "Oxidative phosphorylation", "Photosynthesis chemistry", "Buffers in blood", "Metals in enzymes", "Biomolecular recognition", "Biochemistry problem strategy"],
"25_materials_environment_nuclear_lab": [
"Nuclear stability", "Band of stability", "Radioactive decay", "Alpha decay", "Beta decay", "Gamma emission", "Half-life calculations", "Nuclear equations", "Nuclear fission", "Nuclear fusion", "Binding energy per nucleon", "Radiation detection", "Biological effects of radiation", "Radiocarbon dating", "Medical radioisotopes", "Polymerization", "Addition polymers", "Condensation polymers", "Thermoplastics", "Thermosets", "Elastomers", "Polymer molecular weight", "Glass transition", "Composite materials", "Ceramics", "Metals and alloys", "Nanomaterials", "Quantum dots", "Carbon nanotubes", "Graphene", "Catalysts and green chemistry", "Atom economy", "Renewable feedstocks", "Life-cycle thinking", "Air pollutants", "Water treatment chemistry", "Atmospheric ozone", "Climate chemistry", "Soil chemistry", "Chemical laboratory safety"],
}

# Count checks are performed after the module table is loaded.

out = []
num = 1
for module, titles in MODULES.items():
    for title in titles:
        slug = ''.join(ch.lower() if ch.isalnum() else '-' for ch in title).strip('-')
        while '--' in slug:
            slug = slug.replace('--', '-')
        out.append({"number": num, "module": module, "title": title, "slug": slug})
        num += 1

root = Path(__file__).parent
(root / 'curriculum.json').write_text(json.dumps(out, indent=2) + '\n')

lines = ["# Chemistry Explainer Series: 1,000-Episode Curriculum", "", "This curriculum contains 1,000 self-contained episodes arranged from foundational chemistry through advanced, applied, and interdisciplinary topics.", "", "| No. | Module | Episode title |", "|---:|---|---|"]
for item in out:
    lines.append(f"| {item['number']} | {item['module'].replace('_', ' ').title()} | {item['title']} |")
(root / 'curriculum.md').write_text('\n'.join(lines) + '\n')
print(f'Wrote {len(out)} topics to {root / "curriculum.json"}')
