-- HireSense AI core Supabase schema
-- Run this once in Supabase SQL Editor before enabling database sync.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  full_name text not null default '',
  role text not null default 'candidate'
    check (role in ('candidate', 'recruiter', 'admin')),
  locale text not null default 'en',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.jobs (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  company_key text not null default 'general',
  company_name text not null default '',
  title text not null,
  description text not null,
  required_skills jsonb not null default '[]'::jsonb,
  status text not null default 'practice'
    check (status in ('draft', 'open', 'closed', 'practice')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.applications (
  id uuid primary key default gen_random_uuid(),
  job_id uuid not null references public.jobs(id) on delete cascade,
  candidate_id uuid not null references auth.users(id) on delete cascade,
  resume_text text not null default '',
  resume_path text,
  consented_at timestamptz not null default now(),
  status text not null default 'practice'
    check (status in ('draft', 'submitted', 'interview', 'completed', 'practice')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.interviews (
  id uuid primary key,
  application_id uuid not null references public.applications(id) on delete cascade,
  owner_id uuid not null references auth.users(id) on delete cascade,
  interview_type text not null default 'Mixed',
  company_key text not null default 'general',
  language_key text not null default 'en',
  language_code text not null default 'en-US',
  mode text not null default 'text'
    check (mode in ('text', 'live_voice')),
  status text not null default 'in_progress'
    check (status in ('in_progress', 'completed', 'abandoned')),
  model text not null default '',
  total_questions integer not null default 5
    check (total_questions between 1 and 50),
  progress jsonb not null default '{}'::jsonb,
  metrics jsonb not null default '{}'::jsonb,
  report_markdown text not null default '',
  evidence_assessment jsonb,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.interview_turns (
  id uuid primary key default gen_random_uuid(),
  interview_id uuid not null references public.interviews(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  turn_index integer not null check (turn_index > 0),
  question_number integer not null check (question_number > 0),
  is_followup boolean not null default false,
  question_original text not null,
  transcript_original text not null,
  transcript_confirmed boolean not null default false,
  language_key text not null default 'en',
  language_code text not null default 'en-US',
  english_translation text,
  transcription_engine text not null default 'typed',
  question_source text not null default 'model',
  speech_stats jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (interview_id, turn_index)
);

create table if not exists public.evaluation_scores (
  id uuid primary key default gen_random_uuid(),
  interview_id uuid not null references public.interviews(id) on delete cascade,
  owner_id uuid not null references auth.users(id) on delete cascade,
  dimension text not null,
  score numeric(2,1) check (score is null or score between 1 and 5),
  evidence_excerpt text,
  evidence jsonb not null default '[]'::jsonb,
  reason text not null default '',
  reliability text not null default 'Unavailable',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (interview_id, dimension)
);

create table if not exists public.audit_events (
  id bigint generated by default as identity primary key,
  actor_id uuid references auth.users(id) on delete set null,
  event_type text not null,
  entity_type text not null,
  entity_id uuid,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists jobs_owner_id_idx on public.jobs(owner_id);
create index if not exists applications_candidate_id_idx
  on public.applications(candidate_id);
create index if not exists applications_job_id_idx on public.applications(job_id);
create index if not exists interviews_owner_status_idx
  on public.interviews(owner_id, status, updated_at desc);
create index if not exists interview_turns_interview_idx
  on public.interview_turns(interview_id, turn_index);
create index if not exists evaluation_scores_interview_idx
  on public.evaluation_scores(interview_id);

alter table public.interviews
  add column if not exists language_key text not null default 'en';
alter table public.interview_turns
  add column if not exists language_key text not null default 'en';

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists jobs_set_updated_at on public.jobs;
create trigger jobs_set_updated_at
before update on public.jobs
for each row execute function public.set_updated_at();

drop trigger if exists applications_set_updated_at on public.applications;
create trigger applications_set_updated_at
before update on public.applications
for each row execute function public.set_updated_at();

drop trigger if exists interviews_set_updated_at on public.interviews;
create trigger interviews_set_updated_at
before update on public.interviews
for each row execute function public.set_updated_at();

drop trigger if exists interview_turns_set_updated_at on public.interview_turns;
create trigger interview_turns_set_updated_at
before update on public.interview_turns
for each row execute function public.set_updated_at();

drop trigger if exists evaluation_scores_set_updated_at
on public.evaluation_scores;
create trigger evaluation_scores_set_updated_at
before update on public.evaluation_scores
for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, email, full_name, role)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'full_name', ''),
    'candidate'
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

create or replace function public.protect_profile_role()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if current_user not in ('postgres', 'service_role', 'supabase_admin')
     and new.role is distinct from old.role then
    new.role = old.role;
  end if;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

drop trigger if exists profiles_protect_role on public.profiles;
create trigger profiles_protect_role
before update on public.profiles
for each row execute function public.protect_profile_role();

alter table public.profiles enable row level security;
alter table public.jobs enable row level security;
alter table public.applications enable row level security;
alter table public.interviews enable row level security;
alter table public.interview_turns enable row level security;
alter table public.evaluation_scores enable row level security;
alter table public.audit_events enable row level security;

grant usage on schema public to authenticated;
grant select, insert, update, delete on table
  public.profiles,
  public.jobs,
  public.applications,
  public.interviews,
  public.interview_turns,
  public.evaluation_scores,
  public.audit_events
to authenticated;
grant usage, select on all sequences in schema public to authenticated;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own"
on public.profiles for select to authenticated
using (auth.uid() is not null and id = auth.uid());

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
on public.profiles for update to authenticated
using (auth.uid() is not null and id = auth.uid())
with check (auth.uid() is not null and id = auth.uid());

drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own"
on public.profiles for insert to authenticated
with check (
  auth.uid() is not null
  and id = auth.uid()
  and role = 'candidate'
);

drop policy if exists "jobs_owner_all" on public.jobs;
create policy "jobs_owner_all"
on public.jobs for all to authenticated
using (auth.uid() is not null and owner_id = auth.uid())
with check (auth.uid() is not null and owner_id = auth.uid());

drop policy if exists "applications_candidate_all" on public.applications;
create policy "applications_candidate_all"
on public.applications for all to authenticated
using (auth.uid() is not null and candidate_id = auth.uid())
with check (auth.uid() is not null and candidate_id = auth.uid());

drop policy if exists "applications_recruiter_read" on public.applications;
create policy "applications_recruiter_read"
on public.applications for select to authenticated
using (
  auth.uid() is not null
  and exists (
    select 1 from public.profiles
    where profiles.id = auth.uid()
      and profiles.role in ('recruiter', 'admin')
  )
  and exists (
    select 1 from public.jobs
    where jobs.id = applications.job_id
      and jobs.owner_id = auth.uid()
  )
);

drop policy if exists "interviews_owner_all" on public.interviews;
create policy "interviews_owner_all"
on public.interviews for all to authenticated
using (auth.uid() is not null and owner_id = auth.uid())
with check (auth.uid() is not null and owner_id = auth.uid());

drop policy if exists "interviews_recruiter_read" on public.interviews;
create policy "interviews_recruiter_read"
on public.interviews for select to authenticated
using (
  auth.uid() is not null
  and exists (
    select 1 from public.profiles
    where profiles.id = auth.uid()
      and profiles.role in ('recruiter', 'admin')
  )
  and exists (
    select 1
    from public.applications
    join public.jobs on jobs.id = applications.job_id
    where applications.id = interviews.application_id
      and jobs.owner_id = auth.uid()
  )
);

drop policy if exists "turns_owner_all" on public.interview_turns;
create policy "turns_owner_all"
on public.interview_turns for all to authenticated
using (auth.uid() is not null and user_id = auth.uid())
with check (auth.uid() is not null and user_id = auth.uid());

drop policy if exists "turns_recruiter_read" on public.interview_turns;
create policy "turns_recruiter_read"
on public.interview_turns for select to authenticated
using (
  auth.uid() is not null
  and exists (
    select 1 from public.profiles
    where profiles.id = auth.uid()
      and profiles.role in ('recruiter', 'admin')
  )
  and exists (
    select 1
    from public.interviews
    join public.applications
      on applications.id = interviews.application_id
    join public.jobs on jobs.id = applications.job_id
    where interviews.id = interview_turns.interview_id
      and jobs.owner_id = auth.uid()
  )
);

drop policy if exists "scores_owner_all" on public.evaluation_scores;
create policy "scores_owner_all"
on public.evaluation_scores for all to authenticated
using (auth.uid() is not null and owner_id = auth.uid())
with check (auth.uid() is not null and owner_id = auth.uid());

drop policy if exists "scores_recruiter_read" on public.evaluation_scores;
create policy "scores_recruiter_read"
on public.evaluation_scores for select to authenticated
using (
  auth.uid() is not null
  and exists (
    select 1 from public.profiles
    where profiles.id = auth.uid()
      and profiles.role in ('recruiter', 'admin')
  )
  and exists (
    select 1
    from public.interviews
    join public.applications
      on applications.id = interviews.application_id
    join public.jobs on jobs.id = applications.job_id
    where interviews.id = evaluation_scores.interview_id
      and jobs.owner_id = auth.uid()
  )
);

drop policy if exists "audit_actor_insert" on public.audit_events;
create policy "audit_actor_insert"
on public.audit_events for insert to authenticated
with check (auth.uid() is not null and actor_id = auth.uid());

drop policy if exists "audit_actor_read" on public.audit_events;
create policy "audit_actor_read"
on public.audit_events for select to authenticated
using (auth.uid() is not null and actor_id = auth.uid());

drop function if exists public.start_practice_interview(
  uuid, text, text, text, text, text, text, text, text, text, integer
);

create or replace function public.start_practice_interview(
  p_interview_id uuid,
  p_company_key text,
  p_company_name text,
  p_job_title text,
  p_job_description text,
  p_resume_text text,
  p_language_key text,
  p_language_code text,
  p_interview_type text,
  p_mode text,
  p_model text,
  p_total_questions integer
)
returns table (interview_id uuid, application_id uuid, job_id uuid)
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_job_id uuid;
  v_application_id uuid;
begin
  if v_user_id is null then
    raise exception 'Authentication is required';
  end if;
  if p_interview_id is null then
    raise exception 'Interview id is required';
  end if;

  insert into public.jobs (
    owner_id,
    company_key,
    company_name,
    title,
    description,
    status
  )
  values (
    v_user_id,
    left(coalesce(p_company_key, 'general'), 80),
    left(coalesce(p_company_name, ''), 160),
    left(coalesce(nullif(p_job_title, ''), 'Practice role'), 160),
    left(coalesce(p_job_description, ''), 60000),
    'practice'
  )
  returning id into v_job_id;

  insert into public.applications (
    job_id,
    candidate_id,
    resume_text,
    status,
    consented_at
  )
  values (
    v_job_id,
    v_user_id,
    left(coalesce(p_resume_text, ''), 60000),
    'practice',
    now()
  )
  returning id into v_application_id;

  insert into public.interviews (
    id,
    application_id,
    owner_id,
    interview_type,
    company_key,
    language_key,
    language_code,
    mode,
    status,
    model,
    total_questions,
    progress
  )
  values (
    p_interview_id,
    v_application_id,
    v_user_id,
    left(coalesce(p_interview_type, 'Mixed'), 50),
    left(coalesce(p_company_key, 'general'), 80),
    left(coalesce(p_language_key, 'en'), 20),
    left(coalesce(p_language_code, 'en-US'), 20),
    case when p_mode = 'live_voice' then 'live_voice' else 'text' end,
    'in_progress',
    left(coalesce(p_model, ''), 160),
    greatest(1, least(coalesce(p_total_questions, 5), 50)),
    jsonb_build_object(
      'current_question_num', 1,
      'awaiting_question', true,
      'awaiting_followup', false
    )
  );

  insert into public.audit_events (
    actor_id,
    event_type,
    entity_type,
    entity_id
  )
  values (
    v_user_id,
    'interview_started',
    'interview',
    p_interview_id
  );

  return query select p_interview_id, v_application_id, v_job_id;
end;
$$;

revoke all on function public.start_practice_interview(
  uuid, text, text, text, text, text, text, text, text, text, text, integer
) from public;
grant execute on function public.start_practice_interview(
  uuid, text, text, text, text, text, text, text, text, text, text, integer
) to authenticated;

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'resumes',
  'resumes',
  false,
  10485760,
  array['application/pdf']::text[]
)
on conflict (id) do update
set public = false,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "resume_objects_owner_select" on storage.objects;
create policy "resume_objects_owner_select"
on storage.objects for select to authenticated
using (
  bucket_id = 'resumes'
  and (storage.foldername(name))[1] = auth.uid()::text
);

drop policy if exists "resume_objects_owner_insert" on storage.objects;
create policy "resume_objects_owner_insert"
on storage.objects for insert to authenticated
with check (
  bucket_id = 'resumes'
  and (storage.foldername(name))[1] = auth.uid()::text
);

drop policy if exists "resume_objects_owner_update" on storage.objects;
create policy "resume_objects_owner_update"
on storage.objects for update to authenticated
using (
  bucket_id = 'resumes'
  and (storage.foldername(name))[1] = auth.uid()::text
)
with check (
  bucket_id = 'resumes'
  and (storage.foldername(name))[1] = auth.uid()::text
);

drop policy if exists "resume_objects_owner_delete" on storage.objects;
create policy "resume_objects_owner_delete"
on storage.objects for delete to authenticated
using (
  bucket_id = 'resumes'
  and (storage.foldername(name))[1] = auth.uid()::text
);
